/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Harold.Llanos (https://sketchfab.com/Harold.Llanos)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/perro-lowpoly-lowpoly-dog-a5e68d1f73d74a0f959150be8d0ca31c
Title: Perro Lowpoly - lowpoly dog
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import dogScene from '../assets/perro_lowpoly_-_lowpoly_dog/scene.gltf'

const Dog = (props) => {
  const { nodes, materials } = useGLTF(dogScene)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_0.geometry}
          material={materials.Root}
          position={[-1.313, 0, 0.264]}
          scale={0.315}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_0.geometry}
          material={materials.Root}
          position={[-3.37, 0, -0.47]}
          rotation={[0, -0.052, 0]}
          scale={0.465}
        />
      </group>
    </group>
  )
}

useGLTF.preload(dogScene)

export default Dog
